ALTER TABLE users
    ADD COLUMN IF NOT EXISTS pd_consent BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS pd_consent_at TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS pd_consent_version VARCHAR(50),
    ADD COLUMN IF NOT EXISTS terms_accepted_at TIMESTAMPTZ NULL,
    ADD COLUMN IF NOT EXISTS terms_version VARCHAR(50),
    ADD COLUMN IF NOT EXISTS privacy_version VARCHAR(50);


